### ISSUE TITLE
unrecognized option `-background transparent'

### ISSUE THREAD

**Issue by RobWu** [maxim/skeptick#4]
Try to run a converter from svg to png.

```ruby
    command = convert(to: "#{file_name}.png") do
      set '-background transparent'
      image "#{file_name}.svg"
    end
    command.run
```

But get always error (no difference when i change order of 'image ...' and set '...')
```ruby
convert: unrecognized option `-background transparent' @ error/convert.c/ConvertImageCommand/853.
```

When i run the output in the console or with method 'system' (f.e system command.to_s) it works fine.

**Comment by maxim** [comment]
@RobWu Everything you pass to set is escaped, including spaces, so you gotta separate your arguments. Either of the following will work:

```ruby
# these 2 are equivalent
set :background, 'transparent'
set '-background', 'transparent'
```

**Comment by maxim** [comment]
@RobWu I noticed I still had a couple of outdated examples in the README, so I cleaned it up + added clarification about your case. https://github.com/maxim/skeptick#set

**Comment by RobWu** [comment]
Cool, thanks
